-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 19:31:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parkmanager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parkmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parkmanager` DEFAULT CHARACTER SET utf8 ;
USE `parkmanager` ;

-- -----------------------------------------------------
-- Table `parkmanager`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parkmanager`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkmanager`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parkmanager`.`admin` (
  `idAdmin` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkmanager`.`park`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parkmanager`.`park` (
  `idpark` INT NOT NULL AUTO_INCREMENT,
  `avaible` VARCHAR(45) NOT NULL,
  `timeUp` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `floor` DECIMAL(0) NOT NULL,
  `user_idUser` INT NOT NULL,
  `admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idpark`),
  INDEX `fk_park_user1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_park_admin1_idx` (`admin_idAdmin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkmanager`.`park`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parkmanager`.`park` (
  `idpark` INT NOT NULL AUTO_INCREMENT,
  `avaible` VARCHAR(45) NOT NULL,
  `timeUp` VARCHAR(45) NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `floor` DECIMAL(0) NOT NULL,
  `user_idUser` INT NOT NULL,
  `admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idpark`),
  INDEX `fk_park_user1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_park_admin1_idx` (`admin_idAdmin` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
